spring:
  application:
    name: mcp-java-server

  main:
    web-application-type: reactive

server:
  port: 18060

mcp:
  server:
    name: "mcp-java-server"
    version: "1.0.0"
    description: "MCP Java Server Implementation for Learning"

    transport:
      type: STDIO

    capabilities:
      tools: true
      resources: true
      prompts: true
      logging: true
      resourceSubscriptions: false

logging:
  level:
    com.example.mcp: DEBUG
    reactor: WARN
    org.springframework: INFO

  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"

  file:
    name: logs/mcp-server.log

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true