version: '3.8'

services:
  mcp-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: mcp-java-server:latest
    container_name: mcp-java-server

    # Environment variables
    environment:
      - JAVA_OPTS=-Xmx512m -Xms256m -XX:+UseG1GC
      - SPRING_PROFILES_ACTIVE=docker
      - MCP_SERVER_NAME=mcp-java-server-docker
      - MCP_SERVER_VERSION=1.0.0

    # Volumes for persistent data
    volumes:
      - mcp_logs:/app/logs
      - mcp_files:/app/mcp-files
      - ./config:/app/config:ro

    # Network configuration
    networks:
      - mcp-network

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'

    # Restart policy
    restart: unless-stopped

    # Health check
    healthcheck:
      test: ["CMD", "pgrep", "-f", "mcp-java-server"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Add a simple web interface or monitoring
  portainer:
    image: portainer/portainer-ce:latest
    container_name: mcp-portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    networks:
      - mcp-network
    restart: unless-stopped
    profiles:
      - monitoring

# Named volumes for data persistence
volumes:
  mcp_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/logs

  mcp_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/mcp-files

  portainer_data:
    driver: local

# Network configuration
networks:
  mcp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16